name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "a68327127a36a3280640419a985e4171"
TURN_SERVICE_ID = "33f3b33b552c3864909b397ac6d21139"

# Optional vars
# OPENAI_MODEL_ENDPOINT = ""

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`

# Optional secrets:
# OPENAI_API_TOKEN = ""
